# Generated by Django 2.2.5 on 2020-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('itens', models.CharField(choices=[('F', 'Frango'), ('M', 'Maionese'), ('C', 'Carne'), ('T', 'Tomate'), ('A', 'Arroz'), ('FE', 'Feijão'), ('FR', 'Frios'), ('B', 'Bebidas'), ('N', 'Nenhuma das opções')], max_length=5)),
                ('datacompra', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
