# Generated by Django 2.2.5 on 2020-04-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20200405_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercado',
            old_name='titulo',
            new_name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.Mercado'),
        ),
        migrations.AddField(
            model_name='mercado',
            name='clientes',
            field=models.ManyToManyField(help_text='Cliente:', to='contas.Cliente'),
        ),
        migrations.AddField(
            model_name='mercado',
            name='quantidade',
            field=models.IntegerField(choices=[('F', 'Frango'), ('M', 'Maionese'), ('C', 'Carne'), ('T', 'Tomate'), ('A', 'Arroz'), ('FE', 'Feijão'), ('FR', 'Frios'), ('B', 'Bebidas'), ('N', 'Nenhuma das opções')], help_text='Quantidade ', null=True),
        ),
    ]
