# Generated by Django 2.2.5 on 2020-04-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_remove_cliente_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
