# Generated by Django 2.2.5 on 2020-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20200406_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercado',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
