# Generated by Django 2.2.5 on 2020-04-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_auto_20200406_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='mercado',
            name='clientes',
        ),
        migrations.AddField(
            model_name='mercado',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.Cliente'),
        ),
    ]
