# Generated by Django 2.2.5 on 2020-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20200406_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercado',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
